--- 
abstract: a working (require "Class::Name") and more
author: 
  - Shawn M Moore, C<< <sartak at bestpractical.com> >>
build_requires: 
  Test::Exception: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.70
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Class-Load
no_index: 
  directory: 
    - inc
    - t
version: 0.02
