---
abstract: "a working (require \"Class::Name\") and more"
author:
  - 'Shawn M Moore, C<< <sartak at bestpractical.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Load
no_index:
  directory:
    - inc
    - t
requires:
  Scalar::Util: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bestpractical/class-load
version: 0.06
