---
abstract: "a working (require \"Class::Name\") and more"
author:
  - 'Shawn M Moore <sartak at bestpractical.com>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200013, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Load
requires:
  Scalar::Util: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Class-Load
  repository: git://github.com/autarch/class-load.git
version: 0.07
